# class agnostic in RPN

MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  #WEIGHT: "/home/w/workspace/DetectionHub/tools/output_obj-focal-loss-3/model_final.pth"
  BACKBONE:
    CONV_BODY: "Densebox32T"
    OUT_CHANNELS: 128

  RPN:
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FG_IOU_THRESHOLD: 0.5
    BG_IOU_THRESHOLD: 0.3
    BATCH_SIZE_PER_IMAGE: 512

  ROI_BOX_HEAD:
    NUM_CLASSES: 2
    FEATURE_EXTRACTOR: "DenseboxRFCNROIFeatureExtractor32T"
    PREDICTOR: "RFCNPredictor"
    POOLER_TYPE: "PSROI"
    POOLER_RESOLUTION: 3

DATASETS:
  TRAIN: ("global_wheat.yaml", )
  TEST: ("global_wheat.yaml",)

INPUT:
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.5

SOLVER:
  BASE_LR: 0.008
  STEPS: (18000, 25000)
  MAX_ITER: 30000
  IMS_PER_BATCH: 32
  CHECKPOINT_PERIOD: 1500
  WEIGHT_DECAY: 0.0005

OUTPUT_DIR: "output_obj-focal-loss-3"


